# PROYECTO DE SEMANA 03 
def ejer1():
    NOMBRE = input("INGRSE SU NOMBRE:")
    CARRERA = input("INGRESE SU CARRERA:")

    print(f"\n TU NOMBRE ES {NOMBRE} BIENVENIDO(A) A TU PRIMERA CLASE DE {CARRERA}")

ejer1()
